language: python
sudo: false
env:
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=1.11
python:
  - 2.7
  - 3.6
  - pypy
matrix:
  exlude:
    - python: 2.7
      env: DJANGO_VERSION=2.0
    - python: pypy
      env: DJANGO_VERSION=2.0
install:
  - pip install django==$DJANGO_VERSION
  - pip install codecov six
  - python setup.py install
script: make coverage
after_success:
  - codecov